#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.ashokgelal.segmentedcontrol.Resource", IsApplication=false)]

namespace com.ashokgelal.segmentedcontrol
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int radio_button_selected_color = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int radio_button_unselected_color = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public static int radio_button_conner_radius = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int button_text_color = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int radio_checked_default = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int radio_checked_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int radio_checked_middle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int radio_checked_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int radio_unchecked_default = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int radio_unchecked_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int radio_unchecked_middle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int radio_unchecked_right = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int RadioButton = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
